config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    resources :admin_users
    resources :users
    resources :social_medias, only: %i[new create edit update]
    resources :services, except: %i[destroy]
    resources :causes, only: %i[new create edit update]
    resources :categories, only: %i[new create edit update]
    resources :locations, except: %i[index]
    resources :location_services, only: %i[show create]
    resources :office_hours, except: %i[index]
    resources :messages, only: %i[index show]
    resources :organization_admins
    resources :phone_numbers, except: %i[index]
    resources :newsletters do
      post :mark_all_as_added, on: :collection
    end
    root to: "admin_users#index"
    resources :organizations do
      collection do
        get :upload
        post :import
        get :check_ein
      end
    end
    resource :export_locations, only: :new
    resources :blogs do
      member do
        patch :publish
        patch :unpublish
        post :set_cover
        post :set_thumbnail
      end
    end
  end

  devise_for :admin_users
  devise_for :users, controllers: {confirmations: "confirmations"}

  devise_scope :user do
    get "signup" => "devise/registrations#new"
    get "signin" => "devise/sessions#new"
  end

  get "/contact" => "contact_messages#new", :as => :new_contact_message
  post "/contact" => "contact_messages#create", :as => :create_contact_message

  post "newsletter/signup", to: "newsletters#create", as: :newsletter_signup
  get "newsletter/verify/:token", to: "newsletters#verify", as: :verify_newsletter_subscription

  get "/nonprofit" => "nonprofit_requests#new", :as => :new_nonprofit_request
  post "/nonprofit" => "nonprofit_requests#create", :as => :create_nonprofit_request

  get "search" => "searches#show"
  get "termsofuse" => "terms_and_conditions#show", :as => :terms_of_use
  resource :map_popup, only: [:new]
  resource :search_preview, only: [:show]
  resources :search_exports, only: [:create]

  resources :users, only: [:update, :show] do
    resources :blogs, only: [:index], module: :users
  end
  resources :reset_password, only: %i[new]

  resources :locations, only: %i[index new show destroy]

  resources :organizations, only: %i[edit update] do
    get :check_ein, on: :collection
    resources :locations, only: %i[index new create]
    member do
      get "delete_upload/:upload_id", action: :delete_upload
    end
  end

  resources :blogs do
    resources :comments, only: [:create, :edit, :update, :destroy, :show]
    resources :favorite_blogs, only: :create
    resources :blog_likes, only: :create
  end

  resources :favorite_blogs, only: :destroy
  resources :blog_likes, only: :destroy

  resources :favorite_locations, only: %i[create destroy]
  resources :alerts, only: %i[new create edit update destroy]
  resources :causes, param: :name
  get "discover" => "causes#index", :as => :discover
  get "discover/:name" => "causes#show", :as => :discover_show
  resource :my_account, only: %i[show]
  resource :about_us, only: %i[show]
  resource :faqs, only: %i[show]
  resource :donate, only: %i[show]
  resource :privacy_policy, only: %i[show]
  resource :infowindow, only: :new
  resources :autocomplete, only: %i[index]

  root to: "home#index"

  # Custom routes for city-based search
  get "/atlantic-city", to: "cities#show", city: "Atlantic City", as: :atlantic_city
  get "/nashville", to: "cities#show", city: "Nashville", as: :nashville
  get "/los-angeles", to: "cities#show", city: "Los Angeles", as: :los_angeles

  get "redirect", to: "redirection#notice_external_link", as: :redirect

  # Health check for load balancer / Kamal
  get "up", to: "health#show", as: :health_check
end

app/controllers/nonprofit_requests_controller.rb
# frozen_string_literal: true

class NonprofitRequestsController < ApplicationController
  skip_after_action :verify_authorized
  skip_before_action :authenticate_user!
  invisible_captcha only: [:create]

  def new
    @message = Message.new
  end

  def create
    @message = build_message
    if verify_recaptcha(model: @message) && @message.save
      handle_newsletter_subscription if params[:subscribe_to_newsletter] == "1"

      flash[:notice] = "Your message was successfully sent!"
      redirect_to root_path
    else
      flash.now[:error] = "Something went wrong"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def build_message
    DeliveringMessage.new(
      Message.new(message_params)
    )
  end

  def message_params
    params.require(:message).permit(
      :name, :email, :phone, :subject, :organization_name,
      :organization_website, :organization_ein, :profile_admin_name,
      :profile_admin_email, :content
    )
  end

  def handle_newsletter_subscription
    email = params.dig(:message, :email)&.downcase&.strip
    return if email.blank?

    newsletter = Newsletter.find_or_initialize_by(email: email)

    if newsletter.new_record?
      newsletter.save
      NewsletterMailer.verification_email(newsletter).deliver_later
    elsif !newsletter.verified?
      NewsletterMailer.verification_email(newsletter).deliver_later
    end
  end
end

app/views/nonprofit_requests/new.html.slim
.main.flex.flex-col.items-center
  h2 class="pt-6 pb-4 text-2xl font-bold text-center md:pt-16 md:mt-2 md:pb-9 text-gray-3"
    | Add or Claim a Nonprofit

  p class="px-8 pb-7 mx-auto max-w-2xl text-center sm:text-lg sm:pb-9 text-gray-3"
    | Giving Connection is a platform designed to connect people with nonprofits in their communities.
  p class="px-8 pb-7 mx-auto max-w-2xl text-center sm:text-lg sm:pb-9 text-gray-3"
    |  In order to create a nonprofit profile that is listed in Giving Connection's search results, a representative from your nonprofit should fill out the following form.
  p class="px-8 pb-7 mx-auto max-w-2xl text-center sm:text-lg sm:pb-9 text-gray-3"
    |  After we verify the nonprofit organization, we will contact the representative listed below to set up an account. You should expect to hear back from us within 3-5 business days.

  div class="md:hidden -z-1"
    div class="absolute top-0 left-0 -z-1"
      = inline_svg_tag 'mob-blur-left-contact.svg', class:"w-10/12 xs:w-full"
    div class="absolute top-0 right-0 -z-1"
      = inline_svg_tag 'mob-blur-right-contact.svg', size:"169*248"

  div class="hidden md:flex"
    div class="absolute top-0 left-0 pl-20 lg:pl-32 -z-1 xl:pl-80"
      = inline_svg_tag 'desk-blur-left-contact.svg', size:"523*419"
    div class="absolute top-0 inset-x-1/2 -z-1"
      = inline_svg_tag 'desk-blur-right-contact.svg', size:"258*248"

  = form_with model: @message, url: create_nonprofit_request_path, method: :post, data: { controller: 'contact-form', "turbo": false} do |f|
    .c-form class="gap-6 pb-11 md:pb-36"
      - if @message.errors.any?
          div class="w-full"
            p class="italic font-semibold text-red-500"
              | Please review the problems below:
            ul
              - @message.errors.full_messages.each do |message|
                li class="text-sm text-red-500"
                  = "- #{message}"
      div class="w-full"
        = f.label :name, "*Name"
        = f.text_field :name, class:"c-input", required: true
      div class="w-full"
        = f.label :email, "*Email"
        = f.email_field :email, class:"c-input", required: true
      div class="w-full"
        = f.label :phone
        = f.telephone_field :phone, class: "c-input"
      div class="w-full"
        = f.label :subject, "*Subject/Purpose of Contact"
        = f.select :subject,\
        [['I’m looking for help from a nonprofit organization.', '1'], ['I want to add a nonprofit to Giving Connection.', '2'],['I want to claim ownership of a nonprofit profile on Giving Connection.', '3'], ['Other', '4']],\
        {include_blank: "Select a subject"}, {class: "c-input pr-7 bg-white", required: true, data: { action: "change->contact-form#subjectSelected",'contact-form-target': 'subject'}}

      div class="w-full"
        = f.label :organization_name, "*Organization Name"
        = f.text_field :organization_name, class:"c-input", required: true
      div class="w-full"
        = f.label :organization_website, "Organization Website"
        = f.text_field :organization_website, class:"c-input", placeholder:"Your Website"
      div class="w-full"
        = f.label :organization_ein, "Organization EIN"
        = f.text_field :organization_ein, class:"c-input", placeholder:"Your Organization EIN"
      div class="w-full"
        = f.label :profile_admin_name, "*Profile Admin Name"
        p class="mt-1.5 text-xs leading-normal"
          | Your profile admin is the person who will be updating the page information.
        = f.text_field :profile_admin_name, class:"c-input", required: true
      div class="w-full"
        = f.label :profile_admin_email, "*Profile Admin Email"
        = f.text_field :profile_admin_email, class:"c-input", required: true

      div class="w-full"
        = f.label :content, "*Message"
        = f.text_area :content, class:"c-input h-40", data: { 'contact-form-target': 'message'}, required: true
      // Honeypot
      = invisible_captcha
      div class="w-full"
        = recaptcha_tags

      div class="mt-3"
        = f.submit "Send message", class:"c-button hover:bg-seafoam-light transition"