config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    resources :admin_users
    resources :users
    resources :social_medias, only: %i[new create edit update]
    resources :services, except: %i[destroy]
    resources :causes, only: %i[new create edit update]
    resources :categories, only: %i[new create edit update]
    resources :locations, except: %i[index]
    resources :location_services, only: %i[show create]
    resources :office_hours, except: %i[index]
    resources :messages, only: %i[index show]
    resources :organization_admins
    resources :phone_numbers, except: %i[index]
    resources :newsletters do
      post :mark_all_as_added, on: :collection
    end
    root to: "admin_users#index"
    resources :organizations do
      collection do
        get :upload
        post :import
        get :check_ein
      end
    end
    resource :export_locations, only: :new
    resources :blogs do
      member do
        patch :publish
        patch :unpublish
        post :set_cover
        post :set_thumbnail
      end
    end
  end

  devise_for :admin_users
  devise_for :users, controllers: {confirmations: "confirmations"}

  devise_scope :user do
    get "signup" => "devise/registrations#new"
    get "signin" => "devise/sessions#new"
  end

  get "/contact" => "contact_messages#new", :as => :new_contact_message
  post "/contact" => "contact_messages#create", :as => :create_contact_message

  post "newsletter/signup", to: "newsletters#create", as: :newsletter_signup
  get "newsletter/verify/:token", to: "newsletters#verify", as: :verify_newsletter_subscription

  get "/nonprofit" => "nonprofit_requests#new", :as => :new_nonprofit_request
  post "/nonprofit" => "nonprofit_requests#create", :as => :create_nonprofit_request

  get "search" => "searches#show"
  get "termsofuse" => "terms_and_conditions#show", :as => :terms_of_use
  resource :map_popup, only: [:new]
  resource :search_preview, only: [:show]
  resources :search_exports, only: [:create]

  resources :users, only: [:update, :show] do
    resources :blogs, only: [:index], module: :users
  end
  resources :reset_password, only: %i[new]

  resources :locations, only: %i[index new show destroy]

  resources :organizations, only: %i[edit update] do
    get :check_ein, on: :collection
    resources :locations, only: %i[index new create]
    member do
      get "delete_upload/:upload_id", action: :delete_upload
    end
  end

  resources :blogs do
    resources :comments, only: [:create, :edit, :update, :destroy, :show]
    resources :favorite_blogs, only: :create
    resources :blog_likes, only: :create
  end

  resources :favorite_blogs, only: :destroy
  resources :blog_likes, only: :destroy

  resources :favorite_locations, only: %i[create destroy]
  resources :alerts, only: %i[new create edit update destroy]
  resources :causes, param: :name
  get "discover" => "causes#index", :as => :discover
  get "discover/:name" => "causes#show", :as => :discover_show
  resource :my_account, only: %i[show]
  resource :about_us, only: %i[show]
  resource :faqs, only: %i[show]
  resource :donate, only: %i[show]
  resource :privacy_policy, only: %i[show]
  resource :infowindow, only: :new
  resources :autocomplete, only: %i[index]

  root to: "home#index"

  # Custom routes for city-based search
  get "/atlantic-city", to: "cities#show", city: "Atlantic City", as: :atlantic_city
  get "/nashville", to: "cities#show", city: "Nashville", as: :nashville
  get "/los-angeles", to: "cities#show", city: "Los Angeles", as: :los_angeles

  get "redirect", to: "redirection#notice_external_link", as: :redirect

  # Health check for load balancer / Kamal
  get "up", to: "health#show", as: :health_check
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_after_action :verify_policy_scoped
  skip_before_action :authenticate_user!

  FIRST_VISIT_TEXT = "Connect with a nonprofit today."
  RETURN_VISIT_TEXTS = [
    "Connect with a nonprofit today.",
    "Find your local nonprofit today.",
    "Discover good in your neighborhood.",
    "Your North Star for service."
  ].freeze

  def index
    @search = Search.new
    @main_text = dynamic_main_text
  end

  private

  def dynamic_main_text
    if session[:has_visited_before]
      RETURN_VISIT_TEXTS.sample
    else
      session[:has_visited_before] = true
      FIRST_VISIT_TEXT
    end
  end
end

app/views/home/index.html.slim
main
  section id="search" class="relative py-20 gradient-blue sm:py-24"
    div class ="absolute inset-0"
      = render "stars_background"
    h2 class="z-20 px-12 pb-10 text-3xl font-bold text-center text-white md:mt-8 fade-in md:text-6xl xs:px-20"
      = @main_text
    div class="hidden px-6 pb-6 text-2xl text-center text-white sm:block"
      | Search for nonprofits in Nashville, Atlantic City, & Los Angeles.
    = form_with model: @search, url: search_path, method: :get do |f|
      .c-form class="relative max-w-3xl py-0 mx-auto z-25 c-form sm:px-3 sm:flex-col sm:justify-center sm:max-w-4xl"
        div class="relative flex w-full p-0 divide-x rounded-md mb-7 h-14 c-input sm:mb-0"
          div class="relative flex w-full"
            = f.text_field :keyword, autocomplete: "search", class:"border-none rounded-l-md pl-10 m-0 w-full", placeholder: "Try \"Mental Health Nonprofits\"", data: { test_id: "home_search_input"  }
            = inline_svg_tag 'search-icon.svg', class:"absolute top-1/3 left-4"
          div class="flex m-0 font-medium bg-white cursor-pointer w-52 rounded-r-md" data-controller="dropdown" data-action="click@window->dropdown#hide touchstart@window->dropdown#hide keydown.up->dropdown#previousItem keydown.down->dropdown#nextItem keydown.esc->dropdown#hide" 
            button type="button" class="flex items-center pl-2 md:w-52 border-l-gray" data-action="dropdown#toggle:stop"
              = inline_svg_tag "location-dot.svg", size:"9*9", class:"h-7 mr-2 fill-current"
              p data-geolocation-target="currentLocation"
                = @current_location[:city]&.presence || "Location not found"
            div data-dropdown-target="menu" class="absolute right-0 z-10 flex top-14 w-52"
              ul class="w-full overflow-hidden text-sm bg-white border rounded shadow-lg"
                - @locations.each do |location|
                  li  class="block px-4 py-2 text-gray-3 hover:bg-seafoam" data-action="click->dropdown#toggle click->geolocation#updateLocation" data-dropdown-target="menuItem"
                    = location
                li class="flex items-center block px-4 py-1 font-medium text-gray-3 border-gray-5 hover:bg-seafoam focus:bg-seafoam" data-action="click->dropdown#toggle click->geolocation#getCurrentPosition" data-dropdown-target="menuItem"
                  = inline_svg_tag "my-location.svg", size:"12*12", class:"h-7 mr-2 fill-current text-gray-3"
                  | Search near me
        div
          = f.hidden_field :lat, value: @current_location[:latitude], data: { geolocation_target: "formLatitude" }
          = f.hidden_field :lon, value: @current_location[:longitude], data: { geolocation_target: "formLongitude" }
        div
          = f.submit "Search", class:"c-button c-button--search hover:bg-white transition mx-10 mt-8", data: { test_id: "home_search_btn" }
  section class="pt-6 text-gray-2 sm:pt-10" data-controller="fade-in"
    h2 class="pb-8 text-2xl font-bold text-center uppercase sm:pb-5"
      | How it works
    div class="flex flex-col mx-auto justify-evenly max-w-7xl lg:flex-row xl:px-16"
      div class="max-w-xs mx-auto text-center opacity-0 mb-9 lg:mb-0" data-fade-in-target="fadeInElement" data-delay="500"
        div class="flex items-end mb-2 h-36"
          = inline_svg_tag 'search-needs.svg', class:'mx-auto' 
        h5 class="pb-3 font-bold uppercase md:pb-1"
          | 1. Search for your needs
        p.px-8
          | Enter keywords in the search box above to start your search for nonprofits in your area.
      div.text-center.max-w-xs.mx-auto.mb-14.lg:mb-0.opacity-0 data-fade-in-target="fadeInElement" data-delay="1300"
        div class="flex items-end mb-2 h-36"
          = inline_svg_tag 'connect.svg', class:'mx-auto'
        h5 class="pb-3 font-bold uppercase md:pb-1"
          | 2. Connect with organizations
        p.px-8
          | Browse through nonprofit profiles to find the one that matches your needs.
      div class="max-w-xs mx-auto text-center opacity-0" data-fade-in-target="fadeInElement" data-delay="2100"
        div class="flex items-end mb-2 h-36"
          = inline_svg_tag 'help.svg', class:'mx-auto'
        h5 class="pb-3 font-bold uppercase md:pb-1"
          | 3. Receive help
        p class="px-5"
          | Found a nonprofit that meets your needs criteria? Reach out through the contact information provided on their individual profiles.
  section class="flex flex-col items-center px-6 overflow-hidden"
    div class="relative max-w-xl pt-32 mb-14"
      h2 class="mb-6 text-2xl font-bold text-center text-black uppercase dark:text-white"
        | Browse by causes
      p class="text-center"
        | Use our discovery feature to find nonprofits serving your community. 
        | Select a cause below to learn more about organizations in the Nashville and Atlantic City area providing critical services within your chosen category. 
        | Scroll through listings to browse for nonprofits meeting your needs.
      = inline_svg_tag "browse-causes-green-blur.svg", class: "absolute -left-1/4 top-0 -z-1 w-full", aria_hidden: true
      = inline_svg_tag "browse-causes-purple-blur.svg", class: "absolute -right-1/4 top-0 -z-1 w-full", aria_hidden: true
    nav class="w-full max-w-5xl mb-9"
      = render CausesList::Component.new(causes: Cause.top(limit: 9), \
        icon_svg_options: {class: "w-1/2", aria_hidden: true}, \
        list_options: { class: "grid grid-cols-auto-fill-6.75 justify-items-center gap-y-6"}, \
        cause_options: { class: "group interactive-btn w-24 text-sm transition-colors hover:text-blue-medium font-medium" }, \
        icon_wrapper_options: { class: "thick-icon w-20 h-20 transition-colors group-hover:bg-blue-medium", aria_hidden: true})

    = link_to "see more", discover_path << "/#causes-section", class: "px-10 py-4 rounded-md mb-32 text-white leading-5 uppercase tracking-wider font-bold bg-blue-dark transition-colors hover:bg-blue-medium"
  section class="flex flex-col mx-auto justify-evenly max-w-7xl md:flex-row sm:mb-1 525px:pb-20 md:px-8"
    div class="relative flex flex-col justify-center mb-16 text-center md:mx-0 md:mb-0"
      div class="max-w-sm py-4 mx-auto"
        h2 class="px-10 pb-4 text-2xl font-bold text-center text-black"
          | We want to make living and giving simpler.
        p class="px-4 pt-3 pb-6 md:pb-10"
          | We are a nonprofit search tool connecting you with resources in your community.
        = link_to "Start your search", '#search', class:'bg-blue-dark transition-colors hover:bg-blue-medium c-button inline-block text-white'
      div class="hidden -top-20 -left-32 sm:block sm:absolute -z-1"
        = inline_svg_tag 'lw-desk-blur-left.svg'
      div class="right-0 hidden overflow-hidden -top-40 sm:block sm:absolute xl:-right-28 -z-1"
        = inline_svg_tag 'lw-desk-blur-right.svg'
      div class="absolute -left-6 -z-1 sm:hidden"
        = inline_svg_tag 'lw-mob-blur-left.svg', size:'320*428'
      div class="absolute right-0 overflow-visible -top-40 -z-1 sm:hidden"
        = inline_svg_tag 'lw-mob-blur-right.svg'
    div class="flex justify-center px-0"
      = image_tag 'board-members.png', class:"525px:rounded-xl object-cover h-350px sm:h-full"
  section class="relative bg-seafoam"
    div class="relative max-w-md pb-20 mx-auto text-center"
      h2 class="px-5 pt-20 text-2xl font-bold text-center pb-11 sm:px-0 md:pt-28 text-blue-dark"
        | Are you a nonprofit organization interested in joining our listings?
      = link_to 'Add or Claim a Nonprofit', new_nonprofit_request_path, class:'c-button inline-block my-1 text-white bg-blue-dark transition-colors hover:bg-blue-medium '
    div class="top-0 left-0 hidden -z-1 sm:block sm:absolute"
      = inline_svg_tag 'lc-desk-blur-left.svg'
    div class="top-0 right-0 hidden -z-1 sm:block sm:absolute"
      = inline_svg_tag 'lc-desk-blur-right.svg'
    div class="absolute bottom-0 right-0 -z-1 sm:hidden"
      = inline_svg_tag 'lc-mob-blur-right.svg'
  = render "shared/newsletter"